name: $(Build.DefinitionName) $(Rev:rrrr)

trigger: none

parameters:
  - name: SolutionName
    displayName: "Solution Unique Name"
    type: string

  - name: SolutionImportMode
    displayName: "Solution Import Mode"
    type: string
    default: Modern Upgrade
    values:
    - Modern Upgrade
    - Legacy Upgrade
    - Update 

  - name: OverwriteUnmanagedCustomisations
    displayName: "Overwrite Unmanaged Customisations"
    type: boolean
    default: false

  - name: SkipLowerVersion
    displayName: "Skip Lower Version"
    type: boolean
    default: true

variables:
  - group: Generic Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
  - group: TEST Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
  - group: PROD Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
  - group: HFXDEV Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library.
  - group: HFXTEST Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
  - name: ImportMode
    value: ${{ parameters.SolutionImportMode }}

resources:
  pipelines:
    - pipeline: 'CI-Build'
      source: 'CI Build'

stages:
  - stage: deployToTEST
    condition: eq(variables['Build.SourceBranchName'], 'main')
    dependsOn: []
    displayName: Deploy to TEST (main)
    jobs:
    - deployment: deployToTEST
      variables:
        - group: TEST Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
      pool:
        vmImage: 'windows-latest'
      displayName: "Deploy to TEST"
      environment: 'TEST'
      strategy:
       runOnce:
         deploy:
          steps:
          - template: ../Templates/deploy-solution-template.yml
            parameters:
              SolutionName: ${{ parameters.SolutionName }}
              OverwriteUnmanagedCustomisations: ${{ parameters.OverwriteUnmanagedCustomisations }}
              SkipLowerVersion: ${{ parameters.SkipLowerVersion }}
             
  - stage: deployToPRODMain
    condition: eq(and(variables['Build.SourceBranchName'], 'main'), succeeded('deployToTEST'))
    dependsOn: deployToTEST
    displayName: Deploy to PROD (main)
    jobs:
    - deployment: deployToPROD
      variables:
        - group: PROD Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
      pool:
        vmImage: 'windows-latest'
      displayName: "Deploy to PROD"
      environment: 'PROD'
      strategy:
       runOnce:
         deploy:
          steps:
          - template: ../Templates/deploy-solution-template.yml
            parameters:
              SolutionName: ${{ parameters.SolutionName }}
              OverwriteUnmanagedCustomisations: ${{ parameters.OverwriteUnmanagedCustomisations }}
              SkipLowerVersion: ${{ parameters.SkipLowerVersion }}
    
    - deployment: deployToHFXDEV
      variables:
        - group: HFXDEV Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
      pool:
        vmImage: 'windows-latest'
      displayName: "Deploy to HFXDEV"
      environment: 'HFXDEV'
      strategy:
       runOnce:
         deploy:
          steps:
          - template: ../Templates/prepare-hotfix-env-template.yml
            parameters:
              SolutionName: ${{ parameters.SolutionName }}
    
    - job: resetHotfixBranch
      pool:
        vmImage: 'windows-latest'
      displayName: 'Reset Hotfix Branch'
      steps:
      - template: ../Templates/reset-hotfix-branch-template.yml

  - stage: deployToHFXTEST
    condition: eq(variables['Build.SourceBranchName'], 'hotfix')
    dependsOn: []
    displayName: Deploy to HFXTEST (hotfix)
    jobs:
    - deployment: deployToHFXTEST
      variables:
        - group: HFXTEST Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
      pool:
        vmImage: 'windows-latest'
      displayName: "Deploy to HFXTEST"
      environment: 'HFXTEST'
      strategy:
       runOnce:
         deploy:
          steps:
          - template: ../Templates/deploy-solution-template.yml
            parameters:
              SolutionName: ${{ parameters.SolutionName }}
              OverwriteUnmanagedCustomisations: ${{ parameters.OverwriteUnmanagedCustomisations }}
              SkipLowerVersion: ${{ parameters.SkipLowerVersion }}
             
  - stage: deployToPRODHotfix
    condition: eq(and(variables['Build.SourceBranchName'], 'hotfix'), succeeded('deployToHFXTEST'))
    dependsOn: deployToHFXTEST
    displayName: Deploy to PROD (hotfix)
    jobs:
    - deployment: deployToPROD
      variables:
        - group: PROD Environment Variables # This Variable Group will need creating in your Azure DevOps Project under Pipelines > Library. 
      pool:
        vmImage: 'windows-latest'
      displayName: "Deploy to PROD"
      environment: 'PROD'
      strategy:
       runOnce:
         deploy:
          steps:
          - template: ../Templates/deploy-solution-template.yml
            parameters:
              SolutionName: ${{ parameters.SolutionName }}
              OverwriteUnmanagedCustomisations: ${{ parameters.OverwriteUnmanagedCustomisations }}
              SkipLowerVersion: ${{ parameters.SkipLowerVersion }}
    
